### ISSUE TITLE
Update README section about customising location of Clang

### ISSUE THREAD

**Issue by boguscoder** [lewissbaker/cppcoro#101]
Current README mentions following lines in `config.cake`:
```python
  # If you have built your own version of Clang, you can modify
  # this variable to point to the CMAKE_INSTALL_PREFIX for
  # where you have installed your clang/libcxx build.
  clangInstallPrefix = '/usr'
```
and
```python
  # Set this to the install-prefix of where libc++ is installed.
  # You only need to set this if it is not installed at the same
  # location as clangInstallPrefix.
  libCxxInstallPrefix = None # '/path/to/install'
```
but these lines are not preset there, at least not verbatim, this may be a bit confusing

**Comment by lewissbaker** [comment]
Ah. My apologies for the confusion.

I updated the build system to allow specifying these paths as command-line args some time ago and must have missed updating the README.

You can now specify these paths with following arguments to cake:
```
--clang-executable=clang-8
--clang-install-prefix=/my/clang/install
--libcxx-install-prefix=/my/libcxx/install
```

I'll update the README to reflect these changes.
