### ISSUE TITLE
Add [[nodiscard]] to awaitables

### ISSUE THREAD

**Issue by joemalle** [lewissbaker/cppcoro#104]
Currently there is no warning if you call a function that returns an awaitable but don't call co_await.  At best, there is a runtime diagnostic.  Adding [[nodiscard]] to the awaitable types would make the compiler warn about these mistakes.

I can make a PR if this seems reasonable to you.

**Comment by boimart1** [comment]
I've asked before on the cpp slack:
![image](https://user-images.githubusercontent.com/28604875/55482667-8c9dd780-5614-11e9-8e67-60ded4cce53b.png)
