### ISSUE TITLE
no output of generator in GCC 10.0.1

### ISSUE THREAD

**Issue by expnkx** [lewissbaker/cppcoro#148]
#include"generator.hpp"
#include<iostream>

cppcoro::generator<char const*> gen()
{
	for(std::size_t i{};i!=10;++i)
		co_yield "Hello World\n";
}

int main()
{
	for(char const* sv : gen())
		std::cout<<sv<<'\n';
}

**Comment by OleksandrKvl** [comment]
I observe the same behavior in GCC 10.1.0. Looks like a bug in GCC. This code works:
```c++
cppcoro::generator<char const*> gen2()
{
    for (std::size_t i{}; i != 10; ++i)
    {
        std::cout << "iteration\n";
        co_yield "Hello World\n";
    }
}
```
Another example:
```c++
cppcoro::generator<int> gen3()
{
    int v{};
    for (std::size_t i{}; i != 10; ++i)
    {
        //doesn't work if we use i as a counter
        // co_yield i;
        //works if we use v as a counter
        co_yield v;
        v++;
    }
}
```

**Comment by lewissbaker** [comment]
This is a known bug in gcc and should be fixed in a subsequent version.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95017
