### ISSUE TITLE
Add support for building with clang

### ISSUE THREAD

**Issue by lewissbaker** [lewissbaker/cppcoro#3]
@GorNishanov has been working on adding C++ coroutine support to [clang](https://github.com/GorNishanov/clang) and [llvm](https://github.com/GorNishanov/llvm).

The build system needs to be updated to add support for building this library with clang so that it can be tested on compilers other than MSVC.

As far as I can tell, not all of the changes have been upstreamed to clang yet so I'll need to use a custom build of clang in the mean-time.

**Comment by GorNishanov** [comment]
About 60% in the trunk.

**Comment by lewissbaker** [comment]
I've made some progress towards getting cppcoro building under clang for Windows using libc++.
However, I was still running into some linker issues with unresolved symbols that I need to track down.

I have also been blocked on https://bugs.llvm.org/show_bug.cgi?id=33414 which was causing Clang to go into an infinite loop when compling about half of the test .cpp files. It's possible this bug is only an issue when building with msvc-compatibility mode enabled which could explain why nobody else has run into it yet.

I'll try and get some of the work-in-progress pushed soon.

The snapshot build of Clang for Windows available from http://llvm.org/builds/ should now include enough coroutine support to be dangerous. I may look into having the build-system automatically download and unpack clang from this snapshot build.

**Comment by lewissbaker** [comment]
I've pushed some experimental work-in-progress support for Clang under Linux to the 'clang' branch in 5734b5c2e9ce3e4ba7face9baac0f84cb2c6b6bd.

It compiles all source files except for file and io_service related classes but I'm still yet to get it to successfully link; unresolved symbols. Possibly just me doing something silly while trying to build libc++.

**Comment by lewissbaker** [comment]
The 'clang' branch should now build and pass all tests as of  7db28481ac2544324ff6588bd056dc17c879a71e once you have a clang/libcxx-5.0 dev env setup. Tested under Ubuntu 17.04.

I still need to write up some instructions for building before merging back to master.

**Comment by lewissbaker** [comment]
Clang support is now in 'master' branch.

**Comment by Qix-** [comment]
@lewissbaker the readme should be updated, then - master still states it's "planned" which is not the case (we're building successfully using clang on linux).
