### ISSUE TITLE
Make sync_wait() support arbitrary awaitables not just task/shared_task

### ISSUE THREAD

**Issue by lewissbaker** [lewissbaker/cppcoro#40]

**Comment by lewissbaker** [comment]
Initial version implemented in d07d48eff0f8eed71187238b0942b0f84213fc71 under [generic_ops](https://github.com/lewissbaker/cppcoro/tree/generic_ops) branch.

Note that it is currently failing under MSVC due to what looks like a compiler bug.

MSVC 2017.3 seems to be generating incorrect code for the following statement ([see here](https://github.com/lewissbaker/cppcoro/blob/662f42edd9b7b00f2f6c392524c18c1400b1c583/include/cppcoro/detail/sync_wait_task.hpp#L218))
```
co_yield co_await static_cast<AWAITABLE&&>(awaitable);
```

If the `co_await` expression returns an r-value reference and the `sync_wait_task_promise<RESULT>::yield_value()` call takes an r-value reference then I'm expecting the return-value of `await_resume()` to be passed directly into `yield_value()`.
However, it seems that MSVC is creating a temporary in the `sync_wait_task`'s coroutine-frame and passing that temporary into `yield_value` (at least under (this test)[https://github.com/lewissbaker/cppcoro/blob/662f42edd9b7b00f2f6c392524c18c1400b1c583/test/sync_wait_tests.cpp#L60] which means that the `sync_wait()` returns a dangling reference.

This same test seems to work under Clang.

**Comment by GorNishanov** [comment]
Yay! Looks like a frontend bug. I am tired of getting backend bugs :-)

**Comment by lewissbaker** [comment]
Commit 2080b54c8cdb36c72d4bec3a15eb489b88dcaebe adds a workaround to `task<T>` so that it no longer returns rvalue references from `await_resume()` for fundamental types (arithmetic + pointers) but instead returns a prvalue.

**Comment by lewissbaker** [comment]
A generic `sync_wait()` function is now generally working on the 'generic_ops' branch.

I'm working on some documentation updates for `sync_wait()` to reflect the changes before merging back to master.

**Comment by lewissbaker** [comment]
Closed now that PR #51 has been merged.
