### ISSUE TITLE
Nested coroutines possible??

### ISSUE THREAD

**Issue by akoolenbourke** [lewissbaker/cppcoro#50]
Hi there. Whilst trying to get my head around how coroutines work I had a naive program that ended up bring completely broken. I was wondering if cppcoro has the ability, or could be made to have the ability to build nested coroutines? Here's a toy, pseudo code example to highlight the concept I was trying to achieve.

```
SleepAwaitable sleep_some()
{
    return SleepAwaitable{1s};    // await_suspends launches thread and sleeps, then coro.resume()
}

SleepAwaitable sleep_launcher()
{
    co_await sleep_some();
}
DoAwaitable do_thing()
{
    co_await sleep_launcher();
    co_await sleep_launcher();   // never executed
}

int main()
{
    do_thing();
}
```
It's obvious now, but the SleepAwaitable{} thread resumes after co_await sleep_some then returns back to the thread. The do_thing progress has completely gone.

My main reason for asking as that I intend to have a coroutine of data transfer, but at some point I might need to pass control to another thread pool, have some work done (Potentially with it's own co_await's to other async operations) and then return to the original caller.

Thanks

**Comment by lewissbaker** [comment]
Yes, this sort of thing is certainly possible with cppcoro.

For example:
```c++
#include <cppcoro/task.hpp>
#include <cppcoro/io_service.hpp>
#include <cppcoro/sync_wait.hpp>
#include <cppcoro/when_all.hpp>
#include <chrono>

cppcoro::task<> sleep_some(cppcoro::io_service& service)
{
  using namespace std::chrono_literals;
  co_await service.schedule_after(1s);
}

cppcoro::task<> do_thing(cppcoro::io_service& service)
{
  co_await sleep_some(service);
  co_await sleep_some(service);
}

int main()
{
  cppcoro::io_service service;
  std::thread ioThread{ [&] { service.process_events(); } };
  cppcoro::sync_wait(do_thing(service));
  service.stop();
  ioThread.join();
  return 0;
}
```

One thing to be careful of is that the call to a coroutine will return when the coroutine first suspends.
In your example, the call to `do_thing()` looks suspicious since it will return the `DoAwaitable` when it suspends at the first `co_await` expression. Unless you have something in `main()` to that waits until the coroutine completes then the program will exit before the operation completes, taking the returned `DoAwaitable` with it.

**Comment by akoolenbourke** [comment]
Thanks. 

In your example, what causes do_thing to continue onto the second co_await sleep_some(service)? The second sleep_some call needs to happen AFTER the first one has finished sleeping (Not when suspended)

**Comment by lewissbaker** [comment]
In `do_thing()` it first calls `sleep_some()` which creates the `task<>` but does not yet start the task.
Then when it `co_await`s the result, the `do_thing()` coroutine is suspended and attaches itself as the continuation for the `sleep_some()` task before starting the `sleep_some()` coroutine associated with the `task`.

The `sleep_some()` coroutine then executes the `co_await service.schedule_after()` expression which suspends the current coroutine and schedules the coroutine for resumption on an I/O thread once the specified time has elapsed.

Once the time has elapsed, an event is dispatched to an I/O thread which will then resume the first `sleep_some()` coroutine which then continues executing from the `co_await` expression that it suspended at and subsequently runs to completion. When this coroutine completes it then resumes its continuation (ie. the `do_thing()` coroutine) which then continues from the first `co_await` expression and executes the next `co_await sleep_some()` expression and does a similar thing (creates a task, awaits it, suspending the current coroutine, and starts the next coroutine, etc.)

Note that the call stack is reversed when the coroutines resume.
When it is first called the call stack looks like:
`main` -> `sync_wait` -> `do_thing` -> `sleep_some`
When that coroutine suspends the call stack unwinds to `sync_wait` which then blocks waiting for the `do_thing` task to complete.

When the first timer fires, the call stack looks like this (executing on an I/O thread):
`process_events` -> `sleep_some` (1) -> `do_thing` -> `sleep_some` (2)
Then it will suspend and the I/O thread will re-enter the event loop.

Once the second timer fires, the call stack looks like:
`process_events` -> `sleep_some` -> `do_thing` -> `sync_wait_completion_handler`

The `sync_wait_completion_handler` signals for the `sync_wait` call in main to return.

**Comment by lewissbaker** [comment]
> Another question, if the series of coroutines are part of an async program, where I can't wait with something like sync_wait, is there a solution with cppcoro?

From your example it seems like you want something like an eagerly-started task (similar to a `std::thread`) where once launched it just continues execution until it completes. This is something that cppcoro used to have but I removed it as one of the design goals for cppcoro is to provide a form of structured concurrency where there is no detached computation.

I do have plans for providing something equivalent in cppcoro but in a more structured way.
See #36 for something similar.

**Comment by akoolenbourke** [comment]
Many thanks Lewis. I've just now finished stepping through and came to the understanding you described. One thing that I was missing in the puzzle (Due to complete confusion on my part) was the fact that a task<> returned from sleep_some can in effect have access to TWO coroutines. That is, sleep_some itself, via the promise  passed as an argument to the task<> constructor in get_return_object(). Then the continuation for coroutine do_thing when do_thing co_awaits on task<> returned from sleep_some.

For some reason I only ever really thought that the one passed from do_thing during await_suspend was all that was available. Additionally, I tend to forget that you get full await semantics in final_suspend.

Re #36, I'll take a look at that.

Thanks again
