### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by neo5167** [lewissbaker/cppcoro#57]
The linux build fails. Cake looks for src/run.py and terminates.

**Comment by lewissbaker** [comment]
Did you check out the git submodules when you cloned the repository?
ie `git clone --recursive`

**Comment by neo5167** [comment]
That worked. But cake fails if I do not use the release=debug setting. Specifically, munmap_chunk() fails with an invalid address. Is this expected?

**Comment by lewissbaker** [comment]
Was this a build failure while running the tests?

There are some known clang bugs that currently cause cppcoro to fail under clang optimised.

https://bugs.llvm.org/show_bug.cgi?id=34897
https://bugs.llvm.org/show_bug.cgi?id=34289

**Comment by neo5167** [comment]
Yes. I will close this issue then since it is already known...
