### ISSUE TITLE
Start top-level task without coroutine context

### ISSUE THREAD

**Issue by grishavanika** [lewissbaker/cppcoro#74]
Hi,

Thank you for great library :)

I have small question:
should there be something like `void start_on(scheduler, task)` helper function that is similar to `resume_on(scheduler, task)`, I guess, but will not return lazy task and start given task on given scheduler once `process_event*()` function called ?
I think, this is also something similar to what ASIO `io_service::post()` does.

Looking into test cases I can't find any way to start executing given task without mentioning `co_await` that will lead to another lazy task. Also, there is `sync_wait()`, but it's blocking :(

Just for example: here is peace of code:

```cpp
cppcoro::io_service ui_executor;
cppcoro::io_service file_executor;

cppcoro::task<> load_file()
{
	auto f = cppcoro::read_only_file::open(file_executor
		, R"(test.txt)");
	// ...
	const auto read = co_await f.read();
	// ...
	co_await ui_executor.schedule();
	window.setTitle("done");
}

int main()
{
	std::thread file_thread([&]
	{
		while (...)
			file_executor.process_one_pending_event();
	});

	while (window.isOpen())
	{
		sf::Event event;
		while (window.pollEvent(event))
		{
		}

		{ // Logic update
			if (!load_started)
			{
				load_started = true;
				load_file(...);
			}
		}

		{ // UI update
			ui_executor.process_one_pending_event();
		}

		{ // Render
			window.display();
		}
	}

	// ...
}
```

`load_file()` is coroutine that need to be resumed by someone since there is no call to `co_await`, because it's top-level function in the `main()`. Also, `sync_wait()` can't be called because it will block UI (or whatever) thread.

There is possible work-around, like this:
```cpp
	load_task = load_file(...);
	load_task.get_starter().start(
		cppcoro::detail::continuation{&dummy, nullptr});
```

but it uses internal function and is not very scalable since `load_task` need to be saved somewhere.

As I said in the beginning, is that possible to have something like:
```cpp
	cppcoro::start_on(file_executor, load_file(...));
```
? Is that make sense ? Or am I missing proper way of doing such things ?

Thanks

**Comment by lewissbaker** [comment]
I've recently added a type called `async_scope` that allows you to start executing multiple operations and later wait for them all to complete. This might help with your particular use-case.

eg.
```c++
cppcoro::io_service ioExecutor;
cppcoro::io_service uiExecutor;

cppcoro::task<> load_file() { ... }

int main()
{
  std::thread ioThread{ [&] { ioExecutor.run(); } };
  cppcoro::async_scope scope;
  while (window.isOpen()) {
    // ...
    if (!loadStarted) {
      scope.spawn(load_file());
      loadStarted = true;
    }
    // ...
  }
  cppcoro::sync_wait(scope.join());
  ioExecutor.stop();
  ioThread.join();
}
```

**Comment by lewissbaker** [comment]
I'll close this for now. Please reopen if you find it doesn't suit your use-case well.
