### ISSUE TITLE
cake build process fails for different code page/locale?

### ISSUE THREAD

**Issue by hoffmale** [lewissbaker/cppcoro#82]
On my system (windows 10 64bit), the cake build script failed to build cppcoro with a cryptic utf8 encoding error, probably caused by the vswhere json result containing German special characters (ö, ä, ß) in the "description" field.

I got it to work by changing the command line code page with chcp (from 850 to 1251) before calling cake.bat, but there might be a more elegant solution.

**Comment by lewissbaker** [comment]
Thanks for the bug report!

I’ll look into the vswhere commandline options to see if I can find a way to control the output encoding of the JSON it produces.

**Comment by lewissbaker** [comment]
Should be fixed in cppcoro/master branch now.

**Comment by lewissbaker** [comment]
Ok, so apparently the -utf8 flag is a brand new thing and only works for recent preview releases of VS 2017.8.

I need to revisit this to allow falling back if vswhere is too old.

**Comment by lewissbaker** [comment]
Fixed (again) in commit a58c79cf8b00df02937be7aa9179c50effc862da
