### ISSUE TITLE
How to build cppcoro library with gcc?  ( Currently using gcc version 7.2.0 (Ubuntu 7.2.0-1ubuntu1~16.04) )

### ISSUE THREAD

**Issue by marcoippolito** [lewissbaker/cppcoro#83]
Hi,
I'm using Ubuntu 16.04 Server edition with upgraded gcc : gcc version 7.2.0 (Ubuntu 7.2.0-1ubuntu1~16.04)
how to build cppcoro library with gcc?

Marco

**Comment by lewissbaker** [comment]
As far as I know, GCC does not yet support the Coroutines TS extensions required to be able to build cppcoro.

Please try compiling with a recent version of the Clang compiler - at least 6.0 but preferably the latest nightly build which has some coroutine-related bug-fixes.
