### ISSUE TITLE
Big executable size overhead

### ISSUE THREAD

**Issue by tkozybski** [lewissbaker/cppcoro#95]
Hello.
When a task calls another task by co_await, my executable size increases by 1Kb for each of them, even the simplest one like this:
`cppcoro::task<> Sleep(const int milliseconds)
`
`    {
`
`       co_await synchronizedContext.schedule_after(std::chrono::milliseconds(milliseconds));
`
`    }`

My guestion is, is there any way i could decrease the size overhead? Or maybe i'm doing something wrong.

I'm using MSVC 15.8.8 x64.

**Comment by lewissbaker** [comment]
Are you seeing this with each call to the same function or is this only for each new functuon you call?

What compile flags are you using?

**Comment by tkozybski** [comment]
Each function call causes the overhead, not just new functions.

Flags are /O2 /GR- /await /await:heapelide

**Comment by lewissbaker** [comment]
Some experiments modifying `io_service_tests.cpp` test "Multiple concurrent timers" to add many calls to `ioService.schedule_after(duration)` shows that the implementation of this call is being inlined and each inlined call is consuming about 300 bytes of program text plus a small amount of extra code needed for cleanup at each new suspend-point.

Some observations:
* 1 call - 212480 bytes (base case)
* 4 calls - 214528 bytes (+ 2048) ~682 bytes per extra call
* 8 calls - 216064 bytes (+ 3584) ~512 bytes per extra call
* 16 calls - 219136 bytes (+ 6656) ~443 bytes per extra call

**Comment by lewissbaker** [comment]
Maybe try sprinking a few `__declspec(noinline)` keywords on some of the functions you are calling to prevent the compiler from inlining them.
